name: Run Scripts on Dev Push and Main Merge

on:
  push:
    branches:
      - master
jobs:
  run-scripts:
    name: Run Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script.sh
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        run: |
          ./script.sh "$SUPER_SECRET"
