name: environment test
on: push

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: 
      name: DEV
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run script.sh
          shell: bash
          run: |
            ./script.sh "${{ env.VAR }}"
  
  PROD:
    needs: [DEV]
    runs-on: ubuntu-latest
    environment:
      name: PROD
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run script.sh
          shell: bash
          run: |
            ./script.sh "${{ env.VAR }}"
